CRUDTEST/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('crudapp.urls'))
]

crudapp/urls.py
from django.urls import path
from .views import *

app_name = 'crudapp'
urlpatterns = [
    path('',Homepage,name='Home'),
    path('delete/<int:id>',delete,name='delete'),
    path('edit/<int:id>',edit,name='edit'),
]

crudapp/models.py
from django.db import models

# Create your models here.

class Student(models.Model):
    Name = models.CharField(max_length=30)
    Course = models.CharField(max_length=30)
    Phone_no = models.PositiveIntegerField()
    FatherName = models.CharField(max_length=30)

    def __str__(self):
        return self.Name

crudapp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import *


class studentReg(forms.ModelForm):
    class Meta():
        model = Student
        fields = "__all__"
        widgets = {
            'Name': forms.TextInput(attrs={'class': 'form-control'}),
            'Course': forms.TextInput(attrs={'class': 'form-control'}),
            'Phone_no': forms.TextInput(attrs={'class': 'form-control'}),
            'FatherName': forms.TextInput(attrs={'class': 'form-control'})
        }

crudapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import *
from .models import *

# Create your views here.
def Homepage(request):
    if request.method=='POST':
        form = studentReg(request.POST)
        if form.is_valid():
            form.save(commit=True)
            form = studentReg()
        else:
            return HttpResponse("error")
    else:

        form = studentReg()
    user_details = Student.objects.all()

    return render(request,'home.html',{"form":form,
                                       'details':user_details,
                                       }
                  )



def delete(request,id):
    obj = Student.objects.get(id=id)
    obj.delete()
    return redirect('/')

def edit(request,id):
    if request.method =='POST':
        user = Student.objects.get(id=id)
        form = studentReg(request.POST,instance=user)
        if form.is_valid():
            form.save(commit=True)
            return redirect('/')
    else:
        user = Student.objects.get(id=id)
        form=studentReg(instance=user)
    return render(request,'edit.html',{'form':form})

templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CRUD | EDIT</title>
    <title>CRUD</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
    <div class="jumbotron">
        <h2>Edit Your Details</h2>
    <div class="row">
        <div class="col-sm-6 ">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}

                <input type="submit" class="btn btn-warning" value="UPDATE">
                <a href="{% url 'crudapp:Home' %} "class="btn btn-info">Home</a></td>
            </form>
        </div>
    </div>

</div>
</div>

</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>CRUD</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>

<body>
       <div class="jumbotron">
            <center>
        <h2><strong>CRUD</strong></h2>
    </center>

    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <form method="post">
                    {% csrf_token %} {{ form.as_p }}
                    <center><input type="submit" value="Add" class="btn btn-success"></center>
                </form>
            </div>
            <div class="col-sm-8">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">id</th>
                            <th scope="col">Name</th>
                            <th scope="col">Course</th>
                            <th scope="col">Phone</th>
                            <th scope="col">Father_Name</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% if details.exists %}
                        {% for user in details %}
                        <tr>
                            <th scope="row">{{ user.id }}</th>
                            <td>{{ user.Name}}</td>
                            <td>{{ user.Course }}</td>
                            <td>{{ user.Phone_no }}</td>
                            <td>{{ user.FatherName }}</td>
                            <td>

                                <a href="{% url 'crudapp:delete' user.id %} "class="btn btn-danger">Delete</a>
                                <a href="{% url 'crudapp:edit' user.id %} "class="btn btn-primary">Edit</a></td>
                        </tr>
                    {% endfor %}

                    {% else %}
                        <th>No users</th>

                    {% endif %}


                    </tbody>
                </table>
            </div>
        </div>

    </div>

       </div>
</body>

</html>